### ISSUE TITLE
Provide a way to broadcast raw transaction for LDK compatibility

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#157]
The LDK library requires a way to broadcast a raw transaction.

To enable this in the language bindings, we'd need to either overload the `broadcast()` function, enabling it to take raw bytes as an argument (currently takes a PSBT), or provide a utility function that would transform a raw transaction into a PSBT (not sure if that can really be done or how to do it yet, will look into it).

**Comment by notmandatory** [comment]
I think [PartiallySignedTransaction::consensus_decode()](https://docs.rs/bitcoin/latest/bitcoin/util/psbt/struct.PartiallySignedTransaction.html#method.consensus_decode) will do what we need.

**Comment by notmandatory** [comment]
This issue came up again as a [request on discord](https://discord.com/channels/753336465005608961/978744259693916230/1054508053996785734).

**Comment by notmandatory** [comment]
I think the cleanest way to make this work is:
1. Create a `Transaction` struct, with a default constructor that takes serialized transaction bytes (as provided by LDK).
2. Add a method to `PartiallySignedTransaction` called `extract_tx()` that returns a `Transaction`.
3. Change the `Blockchain.broadcast()` method to take a `Transaction` instead of a `PartiallySignedBitcoinTransaction`.

This will also keep our API more inline with the rust BDK API.
