### ISSUE TITLE
Wondering why we use Transaction::Confirmed and Transaction::Unconfirmed

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk-ffi#180]
The Rust library does not make such distinction; instead the [`TransactionDetails` struct](https://docs.rs/bdk/latest/bdk/struct.TransactionDetails.html#structfield.transaction) has a field `confirmation_time` which is either `None` if the transaction is unconfirmed or `BlockTime` if it is confirmed.

**Comment by notmandatory** [comment]
I think this was an attempt to make the API easier to use, but I agree we should prefer to align with the original rust bdk API.  So I would support refactoring this only have Transaction.

**Comment by ConorOkus** [comment]
Hi, I'm thinking this might be easier to use with LDK's `Confirm` trait - https://docs.rs/lightning/0.0.110/lightning/chain/trait.Confirm.html cc @tnull

**Comment by tnull** [comment]
> Hi, I'm thinking this might be easier to use with LDK's `Confirm` trait - https://docs.rs/lightning/0.0.110/lightning/chain/trait.Confirm.html cc @tnull

Yeah, honestly, I don't think it makes too much of a difference, especially since `Confirm::transaction_confirmed` requires additional data anyways, which we need to collect before we can call it. While most of them are included in `TransactionDetails`, there are some bits and pieces missing, e.g., the intra-block index of the transaction, or the actual block hash in which it was included, which requires additional lookups.
