### ISSUE TITLE
Expose the payload of an Address

### ISSUE THREAD

**Issue by ConorOkus** [bitcoindevkit/bdk-ffi#319]
When we close a channel in LDK, we want the funds to go directly to a BDK-based on-chain wallet. 

We do this by creating a custom `KeysInterface` where we override the [get_destination_script](https://docs.rs/lightning/0.0.113/lightning/chain/keysinterface/trait.KeysInterface.html#tymethod.get_destination_script) & [get_shutdown_scriptpubkey](https://docs.rs/lightning/0.0.113/lightning/chain/keysinterface/trait.KeysInterface.html#tymethod.get_shutdown_scriptpubkey) methods and return addresses from BDK. See [here](https://github.com/lightningdevkit/ldk-node/blob/adfdc246f244bc69dd4060a6d2c437e68b5200ff/src/wallet.rs#L323) for an example in LDK node. 

We'll need to expose the payload of an address in order to extract the witness programme and eventually create the `ShutdownScript` in LDK. This is less error-prone and cumbersome than getting an address from BDK and creating a new script from that, hashing it, and finally creating LDK‘s `ShutdownScript`

**Comment by notmandatory** [comment]
I'm having a little trouble getting my head around this, is the idea to get the script template used to create receive addresses by BDK? If so LDK would still need to contact BDK to get which index is being used for the xkeys so that it doesn't use one that the BDK wallet has already use for receiving on-chain. I found this function, which given a (non-taproot) `Descriptor` gives you the corresponding `Script`, is that the sort of function you're looking for?

https://docs.rs/miniscript/latest/miniscript/descriptor/struct.Wsh.html#method.ecdsa_sighash_script_code

Once we can figure out what the functions are you need in the rust lib we should be able to expose them for the language bindings.

**Comment by notmandatory** [comment]
Ah thanks, I'll get a PR started.
