### ISSUE TITLE
Add swift package

### ISSUE THREAD

**Issue by artfuldev** [bitcoindevkit/bdk-ffi#41]
Related:
* mozilla/application-services [ADR 0003](https://github.com/mozilla/application-services/blob/main/docs/adr/0003-swift-packaging.md)

**Comment by notmandatory** [comment]
Finally I have some progress on this! I successfully created a Swift package with embedded xcframework containing the bdk rust binaries. My test package works with the example ios app and is here: https://github.com/notmandatory/BitcoinDevKit/releases/tag/0.1.1

@konjoinfinity want to try it out???

**Comment by notmandatory** [comment]
Next steps are: 

  - [ ] try to update build.sh script to use the `xcodebuild` command instead of building the xcframework manually
  - [ ] rename the swift package repo, I think I should call it `bdk-swift` instead of `BitcoinDevKit`
  - [ ] find a way to build `bdk-ffi` libs from the new `bdk-swift` repo, worst case add `bdk-ffi` as a git submodule
  - [ ] move build script steps from `build.sh` in `bdk-ffi` repo to script in `bdk-swift` repo
  - [ ] create github actions to publish bdkFFI xcframework .zip file with corresponding `bdk-swift` package

**Comment by notmandatory** [comment]
Ok I updated the current swift example in the `bdk-ffi` repo in the `xcframework` branch and it's working now with the github hosted `BitcoinDevKit` package.

**Comment by notmandatory** [comment]
Closing this based on testing of `bdk-swift` with x86 and m1 based mac simulator and with real iphone12. See: https://github.com/bitcoindevkit/bdk-swift/pull/2
