### ISSUE TITLE
Support more APIs

### ISSUE THREAD

**Issue by artfuldev** [bitcoindevkit/bdk-ffi#56]
- [ ] #63
- [x] List unspent UTXOs in Wallet with outpoint, txout, keychain; txout includes script pubkey and value
- [ ] List transactions with raw transactions
- [ ] Sign a PSBT with Wallet, optionally assume current blockchain height
- [x] Extract a raw transaction from a PSBT
- [x] Create a transaction with multiple recipients (and fee rate)
- [x] Create a send-all UTXOs transaction (and fee rate)
- [x] Allow configuring optional utxos to include, optional unspendable utxo for transactions
- [ ] Allow adding a spending policy map to transactions

**Comment by thunderbiscuit** [comment]
I want to request a new API to add, but I feel like this issue is a bit too "meta" and doesn't provide space for discussing the features one by one and keeping track of them in the Project board with the milestones. How do you feel about creating single issues for features we want, as we want them? Not saying we should close this one, just now sure how to best leverage it.

**Comment by notmandatory** [comment]
I think we should break this up into separate issues for each new API, once done we should reference those new issues and close this one.

**Comment by thunderbiscuit** [comment]
While most of the list above is now done, we've decided to open new issues when the remaining features are requested.
