### ISSUE TITLE
Figure out how to auto-generate documentation

### ISSUE THREAD

**Issue by artfuldev** [bitcoindevkit/bdk-ffi#57]

**Comment by thunderbiscuit** [comment]
I'm exploring [Dokka](https://github.com/Kotlin/dokka).

The 2 ways I'm currently looking into are:
1. Building a separate module with a "mock" source where all function bodies are empty but the docstrings and function signatures are there. This works, but at the cost of being fully separated from the code, so requires manual updating and support. [Example docs](https://thunderbiscuit.github.io/bdk-kotlin/) coming from [this branch](https://github.com/thunderbiscuit/bdk-kotlin/tree/dokka).
2. Applying the docstrings as a patch _post-build_ on the real bindings file. This may or may not work, I'm not sure yet. One problem is that some of the default constructors take a single parameter (pointer) which is for the bindings but not what we want in the docs, and I don't know if I can manually override that.

**Comment by notmandatory** [comment]
While we wait for `uniffi-rs` to figure out how to auto-generate docs for each supported language, we might try using the [`git diff`](https://git-scm.com/docs/git-diff) to create `.patch` files for adding docs to the generated target language code. Then we add the `.patch` files to the repo and our build script applies them where/when needed. But I still need to try this out to see if it will do what I think.

**Comment by thunderbiscuit** [comment]
Using an idea from @notmandatory of applying a patch to the bindings file I have something working for the bdk-jvm library. Check out the issue discussing it here https://github.com/bitcoindevkit/bdk-kotlin/issues/18.

**Comment by notmandatory** [comment]
Not currently supported by `uniffi-rs` so moving a lower priority to keep tracking.

**Comment by thunderbiscuit** [comment]
I worked on a different approach to patch our problem at least on the Kotlin side of things: I built a library with the correct Kdocs but only with empty function signatures. This is a bit hacky, but because the API doesn't change too fast between releases and this file does not get destroyed/rebuilt by the bindings everytime, we get to keep the docs and work at bettering them. 

We've had a series of questions on the Discord server that basically would have been well served by API docs; I think this strikes a good balance between maintainability and accuracy (potentially less accurate/perfect, much easier to maintain).

[Repo is here](https://github.com/thunderbiscuit/bdk-kotlin-api-docs)
[Resulting docs are here](https://thunderbiscuit.github.io/bdk-kotlin-api-docs/)
