### ISSUE TITLE
Include static libraries for more target triples in `bdk-jvm`

### ISSUE THREAD

**Issue by artfuldev** [bitcoindevkit/bdk-ffi#76]
We need to support the following target triples:

- [ ] aarch64-unknown-linux-gnu	ARM64 Linux (kernel 4.2, glibc 2.17+)
- [ ] i686-pc-windows-gnu	32-bit MinGW (Windows 7+)
- [ ] i686-pc-windows-msvc	32-bit MSVC (Windows 7+)
- [ ] i686-unknown-linux-gnu	32-bit Linux (kernel 2.6.32+, glibc 2.11+)
- [x] aarch64-apple-darwin   ARM64 macOS (11.0+, Big Sur+) https://github.com/bitcoindevkit/bdk-kotlin/pull/5
- [x] x86_64-apple-darwin	64-bit macOS (10.7+, Lion+) https://github.com/bitcoindevkit/bdk-kotlin/pull/5
- [ ] x86_64-pc-windows-gnu	64-bit MinGW (Windows 7+)
- [ ] x86_64-pc-windows-msvc	64-bit MSVC (Windows 7+)
- [x] x86_64-unknown-linux-gnu	64-bit Linux (kernel 2.6.32+, glibc 2.11+)

Reference: https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-1-with-host-tools

**Comment by thunderbiscuit** [comment]
The latest macs are not listed as "tier 1" on the rust compiler page you linked, but it would be great to have it as well. 
The tripe is `aarch64-apple-darwin`.

**Comment by artfuldev** [comment]
Thank you! I was thinking that as a first milestone we need to support the tier 1 targets. We'll be adding support for the more popular platforms. And maybe we should add a small section in documentation to describe how to add custom targets. Do you think that works, @thunderbiscuit ? It will still not be super high priority right now.

**Comment by thunderbiscuit** [comment]
Oh yeah for sure. We should only work on what there is bandwidth for. 

I do think however that a good amount of mac developers will be on the new M1 chip by now, and so I expect it to be a fairly "requested" architecture, even if it's not on the "tier 1" of the Rust compiler. But of course right now there is no pressure. It's just us 🤣 .

Also, I got it to work on mine (was trying to test the tatooine PR), and it turned out that the problem was that rust was building by default for my local architecture (the ARM chip) but actually the library that was required was the `x86_64-apple-darwin` target. I'm just getting used to the new chip, and I see that in a lot of cases it uses Rosetta to emulate x86, so you _think_ you need the ARM version of something but it's looking for the x86...

**Comment by artfuldev** [comment]
Yes! When we get enough requests for it, we would definitely add it.

**Comment by notmandatory** [comment]
Moved to lower priority for now since the most common platforms are currently supported (except for Windows).

**Comment by thunderbiscuit** [comment]
We're closing this now. The most important triples still missing are the
1. x86_64-pc-windows-gnu 64-bit MinGW (Windows 7+)
2. x86_64-pc-windows-msvc 64-bit MSVC (Windows 7+)
and we're keeping track of the issue in #240.
